on:
  schedule:
  - cron: "0 20 ? * 1"
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@v4.0.0
      with: 
        ref: site
    - name: Setup Python
      uses: actions/setup-python@v4.7.0
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install requests
    - name: Run Python script
      shell: python
      run: |
        ./.github/workflows/update.py
    - uses: stefanzweifel/git-auto-commit-action@v4
